MAPMA-WebClient/MAPMA-WebClient/Controllers/BookingController.cs
using MAPMA_WebClient.BookRef;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MAPMA_WebClient.ServiceLayer;

namespace MAPMA_WebClient.Controllers
{
    /// <summary>
    /// <author>
    /// Mick O. B. Andersen
    /// Anders S. Brygger
    /// Peter S. Clausen
    /// Anders B. Larsen
    /// Mads G. Ranzau
    /// </author>
    /// </summary>
    public class BookingController : Controller 
    {

        /// <summary>
        /// Starts the booking by getting the escaperoom with the id
        /// </summary>
        /// <param name="id">The EscapeRoom ID</param>
        /// <returns>Returns the view CreateBooking if customer is logged in and redirects to login if not</returns>
        public ActionResult CreateBooking(int id) {
            EscapeRoomService escs = new EscapeRoomService();
            EscRef.EscapeRoom es = escs.GetEscapeRoom(id);
            ViewBag.TimeList = es.AvalibleTimes;
            ViewBag.EscapeRoom = es;
            HttpCookie cookie = Request.Cookies["User"];

        if(cookie == null) {
                return RedirectToAction("Login", "Customer");
            }

            return View();
        }

        /// <summary>
        /// Countiues the creation of a booking and gives it a date
        /// </summary>
        /// <param name="id">The EscapeRoom ID</param>
        /// <param name="BDate">The Date of the booking</param>
        /// <returns>Returns the view CreateBookingCheck or redirects to CreateBooking if BDate == null and if no freetimes are avalible</returns>
        [HttpPost]
        public ActionResult CreateBookingCheck(int id, DateTime BDate) {
            EscapeRoomService escs = new EscapeRoomService();
            EscRef.EscapeRoom es = escs.GetEscapeRoom(id);
            ViewBag.EscapeRoom = es;
            List<TimeSpan> freetime = escs.FreeTimes(id, BDate);
            if (BDate == null)
            {
                TempData["message"] = "Der er ikke valgt en dato";
                return RedirectToAction("CreateBooking", new { id = id });
            }
            else if (freetime.Count == 0)
            {
                TempData["message"] = "Der ingen tilgængelige booking tider";
                return RedirectToAction("CreateBooking", new { id = id });
            }
            else
            {
                ViewBag.freetimes = freetime;
                ViewBag.ChosenDate = BDate.ToString("dd-MM-yyyy");
            }

            return View();
        }

        /// <summary>
        /// Finishes the booking and puts it in the database
        /// </summary>
        /// <param name="EmployeeID">An employees ID</param>
        /// <param name="username">A Username from the user</param>
        /// <param name="escapeRoomID">The EscapeRoom ID</param>
        /// <param name="BookTime">The Time for the booking</param>
        /// <param name="AmountOfPeople">The Amount of people</param>
        /// <param name="BDate">The Date of the booking</param>
        /// <returns>Returns the View CreateBookingDone</returns>
        [HttpPost]
        public ActionResult CreateBookingDone(int EmployeeID, string username, int escapeRoomID, TimeSpan BookTime, int AmountOfPeople, DateTime BDate)
        {
            EscapeRoomService escs = new EscapeRoomService();
            EscRef.EscapeRoom es = escs.GetEscapeRoom(escapeRoomID);
            ViewBag.EscapeRoom = es;
            List<TimeSpan> freetime = escs.FreeTimes(escapeRoomID, BDate);
            ViewBag.freetimes = freetime;
            BookingService bs = new BookingService();
            HttpCookie cookie = Request.Cookies["User"];
            cookie.Value = username;

            int c = bs.CreateBooking(EmployeeID, username, escapeRoomID, BookTime, AmountOfPeople, BDate);
            if (c == 0) {
                TempData["message"] = "Den tid du prøvede at booke er desværre blevet taget ";
                return RedirectToAction("CreateBooking", new { id = escapeRoomID });
            }
            return View();
        }

        /// <summary>
        /// Gets a booking from the database
        /// </summary>
        /// <param name="escapeRoomID">The EscapeRoom ID</param>
        /// <param name="username">A Username from the user</param>
        /// <param name="BDate">The Date of the booking</param>
        /// <returns>Returns the view GetBooking with the found booking</returns>
        [HttpGet]
        public ActionResult GetBooking (int escapeRoomID, string username, DateTime BDate)
        {
            BookingService bs = new BookingService();
            Booking book = bs.GetBooking(escapeRoomID, username, BDate);
            return View(book);
        }

        /// <summary>
        /// Deletes a Booking form the database
        /// </summary>
        /// <param name="EmployeeID">An employees ID</param>
        /// <param name="username">A Username from the user</param>
        /// <param name="escapeRoomID">The EscapeRoom ID</param>
        /// <param name="BookTime"> The Time for the booking</param>
        /// <param name="AmountOfPeople">The Amount of people</param>
        /// <param name="BDate">The Date of the booking</param>
        /// <returns>Returns the view DeleteBooking</returns>
        [HttpDelete]
        public ActionResult DeleteBooking (int EmployeeID, string username, int escapeRoomID, TimeSpan BookTime, int AmountOfPeople, DateTime BDate)
        {
            BookingService bs = new BookingService();
            bs.DeleteBooking(EmployeeID, username, escapeRoomID, BookTime, AmountOfPeople, BDate);
            return View();
        }

        /// <summary>
        /// Deletes a booking from the customers list of bookings
        /// </summary>
        /// <param name="username">A Username from the user</param>
        /// <param name="escapeRoomID">The EscapeRoom ID</param>
        /// <param name="BookTime"> The Time for the booking</param>
        /// <param name="BDate">The Date of the booking</param>
        /// <returns>Returns a redirects to GetAllBookingFromUser with the deleted booking no longer on the list. If an exception happens redirect to Login with a message</returns>
        [HttpDelete]
        public ActionResult DeleteBookingCustomer(string username, int escapeRoomID, TimeSpan BookTime, DateTime BDate) {
            try {                
                BookingService bs = new BookingService();
                bs.DeleteBookingCustomer(username, escapeRoomID, BookTime, BDate);               

                return RedirectToAction("GetAllBookingFromUser", "Customer");
            }
            catch(NullReferenceException e) {
                TempData["message"] = "du har prøvet at gå til en side hvor man skal være logget ind først. lave en bruger eller log ind.";
                return RedirectToAction("Login", "Customer");
            }
        }

        /// <summary>
        /// Get all the bookings from the database
        /// </summary>
        /// <returns>Returns the view GetAllBookings</returns>
        public ActionResult GetAllBookings() {
            BookingService bs = new BookingService();
           List<Booking> books =  bs.GetAllBookings();
            ViewBag.List = books;
            return View();
        }

    }
}

MAPMA-WebClient/MAPMA-WebClient/Controllers/EscapeRoomController.cs
using MAPMA_WebClient.EscRef;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MAPMA_WebClient.ServiceLayer;
using System.Drawing;
using System.IO;

namespace MAPMA_WebClient.Controllers
{
    /// <summary>
    /// <author>
    /// Mick O. B. Andersen
    /// Anders S. Brygger
    /// Peter S. Clausen
    /// Anders B. Larsen
    /// Mads G. Ranzau
    /// </author>
    /// </summary>
    public class EscapeRoomController : Controller    {

        /// <summary>
        ///  Gets an escaperoom
        /// </summary>
        /// <param name="id">The EscapeRoom ID</param>
        /// <returns>returns the View GetEscapeRoom</returns>
        public ActionResult GetEscapeRoom ( int id )        {

            EscapeRoomService ecss = new EscapeRoomService();
            EscRef.EscapeRoom escr = ecss.GetEscapeRoom(id);
            ViewBag.Escaperoom1 = escr;
            return View();
        }

        /// <summary>
        /// Gets a list of esacperooms
        /// </summary>
        /// <returns>Returns the view GetAllEscapeRoom</returns>
        public ActionResult GetAllEscapeRoom ( )
        {
            EscapeRoomService ecss = new EscapeRoomService();

            //EscapeRoom[] escapeRooms;
            List<EscapeRoom> escapeRooms = ecss.GetAllEscapeRooms();
            ViewBag.List = escapeRooms;
            return View();
        }

        /// <summary>
        /// Shows the picture from an escaperoom
        /// </summary>
        /// <param name="imgArray">the bytes of an img</param>
        /// <returns>Returns an image via the method ByteArrayToImage</returns>
        public Image PicShow(byte[] imgArray) {

            return ByteArrayToImage(imgArray);
        }

        /// <summary>
        /// Converts the bytes to an image
        /// </summary>
        /// <param name="byteArrayIn">the bytes of an img</param>
        /// <returns>Returns the converted image</returns>
        public Image ByteArrayToImage ( byte[] byteArrayIn )
        {
            using (var ms = new MemoryStream(byteArrayIn))
            {
                var returnImage = Image.FromStream(ms);

                return returnImage;
            }
        }


    }
}

MAPMA-WebClient/MAPMA-WebClient/Views/Booking/CreateBooking.cshtml
@*@model MAPMA_WebClient.BookRef.BookingServicesClient*@

<style>
    label#lbCreatEsc{
        width: 100px;
    }
        
        
</style>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script>
        function Checkdate() {
          var today = new Date();
var dd = today.getDate();
var mm = today.getMonth()+1; //January is 0!
var yyyy = today.getFullYear();
 if(dd<10){
        dd='0'+dd
    } 
    if(mm<10){
        mm='0'+mm
    } 

today = yyyy+'-'+mm+'-'+dd;
document.getElementById("date").setAttribute("min", today);      
        };
        
    </script>

<h2>Book rum</h2>
<form action="@Url.Action("CreateBookingCheck")" method="post">
    <input id="escid" type="text" name="id" value="@ViewBag.EscapeRoom.escapeRoomID" readonly hidden /><br /><br />
    <label id="lbCreatEsc">Escaperoom:</label>  <label>@ViewBag.EscapeRoom.name</label><br /><br />
    <label id="lbCreatEsc">Dato :</label>  <input id="date" type="date" name="BDate" min="2020-01-01" required /><br /><br />
    <input class="Button" type="submit" value="book rum" onclick="Checkdate()" />
    <p id="da">@TempData["message"]</p>
    <input id="escid" type="text" name="id" value="@ViewBag.EscapeRoom.escapeRoomID" readonly hidden />
</form>

@*<form method="post" action="@Url.Action("CreateBooking")">
    Medarbejder nr:<input type="text" name="EmployeeID" /><br /><br />
    Brugernavn : <input type="text" name="username" /><br /><br />
    Escaperoom Id: <input id="escid" type="text" name="escapeRoomID" value="@ViewBag.EscapeRoom.escapeRoomID" readonly /><br /><br />
    <select data-bind="TimeSpan" name="BookTime">
        @foreach (TimeSpan item in ViewBag.TimeList) {
            <option value="@item">@item</option>
        }
    </select><br /><br />
    Dato : <input id="date" type="date" name="BDate" onchange = "Checkdate()"   /><br /><br />
       <p  id="da"></p>
               
    
    Antal personer: <input type="text" name="AmountOfPeople" /><br /><br />
    <input class="Button" type="submit" value="book rum" />
</form>*@

<div>
    @Html.ActionLink("Back to List", "GetAllEscapeRoom", "EscapeRoom")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bookingtime.js"></script>
}

MAPMA-WebClient/MAPMA-WebClient/Views/Booking/CreateBookingCheck.cshtml
@*@model MAPMA_WebClient.ServiceLayer.BookingService*@
<style>
    label.Booking{
        display: inline-block;
        width: 200px;
        float: left;
    }
    .indputs {
        display: inline-block;
        float: left;
    }
</style>

@*@{
    ViewBag.Title = "CreateBookingCheck";
}*@
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
<h2>Lav Booking</h2>

<link href="~/Content/Site.css" rel="stylesheet" />


<form method="post" action="@Url.Action("CreateBookingDone")">

    <label class="Booking">Brugernavn : </label> <input class="indputs" type="text" name="username" value="@Request.Cookies["User"].Value.ToString()" readonly /><br /><br />
    <label class="Booking">Escaperoom:</label><input class="indputs" type="text" name="name" value="@ViewBag.EscapeRoom.name" readonly /><br /><br />
    <label class="Booking">Den valgte dato :</label> <input class="indputs" type="text" name="BDate" value="@ViewBag.ChosenDate" readonly /><br /><br />
    <label class="Booking">Tider der kan vælges :</label><select class="indputs" data-bind="TimeSpan" name="BookTime">
        @foreach (TimeSpan item in ViewBag.freetimes) {
            <option value="@item">@item</option>
        }
    </select><br /><br />
    <label class="Booking">Antal personer:</label>  <input class="indputs" type="number" name="AmountOfPeople" required min="1" /><br /><br />
    <input class="Button" type="submit" value="book rum" onclick="@("window.location.herf='"+@Url.Action("GetAllEscapeRoom","EscapeRoom")+"'");" />
    <input type="text" name="escapeRoomID" value="@ViewBag.EscapeRoom.escapeRoomID" readonly hidden />
    <label hidden >Medarbejder nr:</label> <input type="text" name="EmployeeID" value="1" readonly hidden /><br /><br />
</form> 

MAPMA-WebClient/MAPMA-WebClient/Views/Booking/CreateBookingDone.cshtml
@{
    ViewBag.Title = "CreateBookingDone";
}

<h2>CreateBookingDone</h2>